name: buildCSharpSDK

on: 
  push:
    branches: [ develop ]

jobs:
  build-csharp:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: Default is true, switch to false to allow one platform to fail and still run others
      fail-fast: false
      matrix:
        name: [Ubuntu, macOS, Windows]
        include:
        - name: Ubuntu
          os: ubuntu-18.04
        - name: macOS
          os: macos-10.15
        - name: Windows
          os: windows-2019

    steps:
      - name: "Checkout develop Branch"
        uses: actions/checkout@v2
        with:
          ref: develop

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'

      - name: Setup CSharp
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'


      - name: Install conan
        run: |
          python --version
          pip install conan
          conan --version
          echo "Enabling conan revisions and setting parallel_download"
          conan config set general.revisions_enabled=True
          conan config set general.parallel_download=8


      - name: Compile Ubuntu
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -x
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_CSHARP_BINDINGS=ON -DBUILD_NUGET_PACKAGE=OFF \
                -DBUILD_TESTING=OFF -DBUILD_RUBY_BINDINGS=OFF -DBUILD_CLI=OFF \
                -DBUILD_PACKAGE=OFF \
                ../
          
          make -j2


      - name: Compile macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          set -x
          export CC=clang
          export CMAKE_OSX_ARCHITECTURES=x86_64
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_CSHARP_BINDINGS=ON -DBUILD_NUGET_PACKAGE=OFF \
                -DBUILD_TESTING=OFF -DBUILD_RUBY_BINDINGS=OFF -DBUILD_CLI=OFF \
                -DBUILD_PACKAGE=OFF \
                ../

          make -j3


      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'

      - name: Compile Windows
        if: runner.os == 'Windows'
        uses: lukka/run-cmake@v2
        with:
          cmakeGenerator: VS16Win64
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          cmakeBuildType: Release
          cmakeAppendedArgs: '-DCMAKE_BUILD_TYPE=Release -DBUILD_CSHARP_BINDINGS=ON -DBUILD_NUGET_PACKAGE=OFF -DBUILD_TESTING=OFF -DBUILD_RUBY_BINDINGS=OFF -DBUILD_CLI=OFF -DBUILD_PACKAGE=OFF'
          buildDirectory: ${{ github.workspace }}/build
          buildWithCMake: true


      - name: list files
        run: |
          echo "Listing the top directory=========================================="
          ls

          echo "Listing ./build/=========================================="
          ls ./build/

          echo "Listing ./build/Products/=========================================="
          ls -R ./build/Products

          echo "Listing ./build/csharp_wrapper/bin/Release/=========================================="
          ls -R ./build/csharp_wrapper/bin/Release

      - name: Tests
        run: |
          dotnet test csharp/examples/OpenStudio.Tests/OpenStudio.Tests.csproj


      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: CSharp_${{ matrix.name }}
          path: |
            ./build/csharp_wrapper/bin/Release

      - name: Upload artifact generated_sources
        uses: actions/upload-artifact@v2
        with:
          name: CSharp_${{ matrix.name }}_Src
          path: |
            ./build/csharp_wrapper/generated_sources
            ./build/csharp_wrapper/OpenStudio.csproj

      - name: Upload artifact (if failed)
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}_Failed
          path: ./build/csharp_wrapper/

