name: buildCSharpSDK

on: 
  push:
    branches: [ develop ]

jobs:
  build:
    name: "Build and release CSharp SDK"
    runs-on: ubuntu-18.04

    steps:
      - name: "Checkout develop Branch"
        uses: actions/checkout@v2
        with:
          ref: develop

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'

      - name: Setup CSharp
        shell: bash
        run: |
          set -x
          cmake -E make_directory ./build
          wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo apt-get install -y dotnet-sdk-3.1
          
      - name: Install conan
        shell: bash
        run: |
          set -x
          python --version
          pip install conan
          conan --version
          echo "Enabling conan revisions and setting parallel_download"
          conan config set general.revisions_enabled=True
          conan config set general.parallel_download=8

      - name: Compile
        shell: bash
        working-directory: ./build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_CSHARP_BINDINGS=ON -DBUILD_NUGET_PACKAGE=ON \
                -DBUILD_TESTING=ON \
                -DBUILD_PACKAGE=ON  -DCPACK_BINARY_DEB=ON  -DCPACK_BINARY_TGZ=ON \
                -DCPACK_BINARY_IFW=OFF -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_RPM=OFF -DCPACK_BINARY_STGZ=OFF \
                -DCPACK_BINARY_TBZ2=OFF -DCPACK_BINARY_TXZ=OFF -DCPACK_BINARY_TZ=OFF ../
          
          make -j2

      - name: list files
        run: |
          echo "Listing the top directory=========================================="
          ls

          echo "Listing ./build/=========================================="
          ls ./build/

          echo "Listing ./build/Products/=========================================="
          ls ./build/Products

          echo "Listing ./build/csharp_wrapper/=========================================="
          ls -R ./build/csharp_wrapper

      - name: Zip Build Artifact
        run: |
          zip -r OpenStudio_lib.zip ./build/Products
          zip -r OpenStudio_CSharpSDK.zip ./build/csharp_wrapper
          
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: OpenStudio_CSharpSDK
          path: OpenStudio_CSharpSDK.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: OpenStudio_lib
          path: OpenStudio_lib.zip

